pipeline {
    agent any

    stages {
        stage('Clonar repositorio') {
            steps {
                git 'https://github.com/munozhassel/juice-shop.git'
            }
        }
        stage('Instalar dependencias') {
            steps {
                sh 'ls -la'
                sh 'pwd'
                sh 'npm install'
            }
        }
        stage('Empaquetar aplicación') {
            steps {
                sh 'zip -r juice-shop.zip .'
            }
            post {
                always {
                    archiveArtifacts 'juice-shop.zip'
                }
            }
        }
    }

    post {
        always {
            script {
                echo 'La aplicación se ha empaquetado correctamente.'
            }
        }
    }
}
