pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = "AKIARI2GL65TCAO4AYIH"
        AWS_SECRET_ACCESS_KEY = "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"
        AWS_DEFAULT_REGION = "us-east-1" 
    }
    
    stages {
        stage('Validar conexión AWS') {
            steps {
                script {
                    sh 'aws s3 ls'
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/munozhassel/jenkins-learning.git'
            }
        }
        
        stage('Deploy Infrastructure') {
            steps {
                script {
                    dir('lab05-infraestructure') {
                        sh 'terraform init'
                        sh 'terraform plan -out=tfplan'
                        sh 'terraform apply tfplan'
                    }
                }
            }
        }
    }
}
