pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tu-repositorio/infraestructura.git'
            }
        }
        
        stage('Deploy Infrastructure') {
            steps {
                script {
                    dir('lab05-infraestructure') { // ruta correcta de archivos Terraform
                        sh 'terraform init'
                        sh 'terraform plan -out=tfplan'
                        sh 'terraform apply tfplan'
                    }
                }
            }
        }
    }
}
